apiVersion: v1
kind: Secret
metadata:
  name: ${{ values.name }}-postgresql-credentials
  labels:
    app.kubernetes.io/instance: ${{ values.name }}
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ${{ values.name }}-postgresql
    app.kubernetes.io/part-of: ${{ values.appName }}
type: Opaque
stringData:
  username: ${{ values.name }}
  password: ${{ values.name }}-postgres-password

